# Generated by Django 3.2.3 on 2021-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210603_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
