# Generated by Django 3.2.3 on 2021-06-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_sneaker_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sneaker',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='sneaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-07 18:57:42.517205-07'),
            preserve_default=False,
        ),
    ]
