# Generated by Django 3.2.3 on 2021-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_sneaker_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sneaker',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.AddField(
            model_name='sneaker',
            name='value',
            field=models.CharField(default='100', max_length=100),
            preserve_default=False,
        ),
    ]
